### ISSUE TITLE
Section 1: 增加按鈕連到宣言 or Mission Statement or 年度報告

### ISSUE THREAD

**Issue by ttcat** [zbryikt/g0v.asia#1]

**Comment by hereismglee** [comment]
修改建議
From across the World 改為一些更明確知道g0v是什麼的slogan 
例如>> We are Nobodies. Nobody is YOU. 

對主文字些微修改：
g0v is a civic tech community that advocates transparency of information and provides tech solutions to civic problems.  
We are passionate coders, designers, activists, educators, writers and citizens. We believe that a better society requires open data, open government and a open culture that brings everyone together.

新增按鈕文字：
See our Mission Statement and Annual Report.

**Comment by ttcat** [comment]
Don't ask "why nobody do..."
Become the nobody!

**Comment by hereismglee** [comment]
Don't ask "why nobody did xxx"
Nobody is YOU.
